
version: '3.8'

services:
  gestion-usuarios:
    build:
      context: ./microservicios/GestionUsuarios/demo
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - cohousing
    depends_on:
      - postgres-usuarios

  gestion-comunidades:
    build:
      context: ./microservicios/GestionComunidades/demo
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - cohousing
    depends_on:
      - postgres-comunidades

  api-gateway:
    build:
      context: ./microservicios/ApiGateAway/demo
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - cohousing

  frontend:
    build:
      context: ./front-end/co-housing
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - cohousing
    depends_on:
      - gestion-usuarios
    volumes:
      - ./front-end/co-housing:/app
      - /app/node_modules

  recomendador:
    build:
      context: ./microservicios/Recomendador
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - cohousing

  postgres-usuarios:
    image: postgres:14
    environment:
      POSTGRES_USER: cohousing
      POSTGRES_PASSWORD: cohousing123
      POSTGRES_DB: cohousingdb
    ports:
      - "5433:5432"  # Cambié el puerto para evitar conflictos
    networks:
      - cohousing
    volumes:
      - pgdata-usuarios:/var/lib/postgresql/data

  postgres-comunidades:
    image: postgres:14
    environment:
      POSTGRES_USER: cohousing
      POSTGRES_PASSWORD: cohousing123
      POSTGRES_DB: comunidadesdb
    ports:
      - "5434:5432"  # Cambié el puerto para evitar conflictos
    networks:
      - cohousing
    volumes:
      - pgdata-comunidades:/var/lib/postgresql/data

networks:
  cohousing:
    driver: bridge

volumes:
  pgdata-usuarios:
  pgdata-comunidades:
