coverage:
  status:
    project:
      default:
        target: auto
        branches:
          - "*"       # Aplica a todas las ramas
    patch:
      default:
        branches:
          - "*"       # También aplica a todas en los patches
