name: Microservice CI Template

on:
  workflow_call:
    inputs:
      micro_path:
        required: true
        type: string
      micro_name:
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17


      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Build and test microservice
        run: |
          cd ${{ inputs.micro_path }}
          mvn clean package jacoco:prepare-agent test jacoco:report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: alonsodm12/TFG_COHOUSING
          files: ${{ inputs.micro_path }}/target/site/jacoco/jacoco.xml

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd ${{ inputs.micro_path }}
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build --build-arg JAR_FILE=target/${{ inputs.micro_name }}-0.0.1-SNAPSHOT.jar -t $DOCKER_USERNAME/spring-cohousing-${{ inputs.micro_name }}:0.0.1-SNAPSHOT .
          docker push $DOCKER_USERNAME/spring-cohousing-${{ inputs.micro_name }}:0.0.1-SNAPSHOT
